services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotelapp-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5050
    ports:
      - "3000:3000"
    restart: unless-stopped

